ProyectSoftware.Web/Controllers/PlaylistController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjectSoftware.Web.Data;
using ProjectSoftware.Web.Data.Entities;
using ProjectSoftware.Web.DTOs;
using ProyectSoftware.Web.Data;
using System.Linq;
using System.Threading.Tasks;

namespace ProjectSoftware.Web.Controllers
{
    public class PlaylistController : Controller
    {
        private readonly DataContext _context;

        public PlaylistController(DataContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var playlists = await _context.Playlists
                .Include(p => p.Songs)
                .Select(p => new PlaylistDTO
                {
                    Id = p.Id,
                    Name = p.Name,
                    Songs = p.Songs.Select(s => new SongDTO { Title = s.Title, Artist = s.Artist }).ToList()
                })
                .ToListAsync();

            return View(playlists);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(PlaylistDTO playlistDTO)
        {
            if (ModelState.IsValid)
            {
                var playlist = new Playlist(playlistDTO.Name);
                _context.Playlists.Add(playlist);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(playlistDTO);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var playlist = await _context.Playlists.FindAsync(id);
            if (playlist != null)
            {
                _context.Playlists.Remove(playlist);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

ProyectSoftware.Web/Views/Playlist/Create.cshtml
@model ProjectSoftware.Web.DTOs.PlaylistDTO

@{
    ViewData["Title"] = "Crear Nueva Lista de Reproducción";
}

<h2>Crear Nueva Lista de Reproducción</h2>

<form asp-action="Create">
    <div class="form-group">
        <label asp-for="Name" class="control-label"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Crear</button>
</form>

<a asp-action="Index" class="btn btn-secondary">Volver </a>

ProyectSoftware.Web/Views/Playlist/Delete.cshtml
@model ProjectSoftware.Web.DTOs.PlaylistDTO

@{
    ViewData["Title"] = "Eliminar Lista de Reproducción";
}

<h2>Eliminar Lista de Reproducción</h2>

<div>
    <p>¿Estás seguro de que quieres eliminar la lista de reproducción <strong>@Model.Name</strong>?</p>
    <form asp-action="Delete" method="post">
        <input type="hidden" name="id" value="@Model.Id" />
        <button type="submit" class="btn btn-danger">Eliminar</button>
        <a asp-action="Index" class="btn btn-secondary">Cancelar</a>
    </form>
</div>

ProyectSoftware.Web/Views/Playlist/Index.cshtml
@model IEnumerable<ProjectSoftware.Web.DTOs.PlaylistDTO>

<!DOCTYPE html>
<html lang="zxx">
<head>
    <title>SolMusic | HTML Template</title>
    <meta charset="UTF-8">
    <meta name="description" content="SolMusic HTML Template">
    <meta name="keywords" content="music, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Favicon -->
    <link href="/img/favicon.ico" rel="shortcut icon" />

    <!-- Google font -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,300i,400,400i,500,500i,600,600i,700,700i&display=swap" rel="stylesheet">

    <!-- Stylesheets -->
    <link rel="stylesheet" href="/theme/playlist/css/font-awesome.min.css" />
    <link rel="stylesheet" href="/theme/playlist/css/owl.carousel.min.css" />
    <link rel="stylesheet" href="/theme/playlist/css/slicknav.min.css" />

    <!-- Main Stylesheets -->
    <link rel="stylesheet" href="/theme/playlist/css/style.css" />

    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Header section -->
    <header class="header-section clearfix">
        <a href="index.html" class="site-logo">
            <img src="/theme/playlist/img/logo.png" alt="">
        </a>
        <ul class="main-menu">
            <li><a href="@Url.Action("Dashboard", "Home")">Inicio</a></li>
            <li>
                <a href="#">Pages</a>
                <ul class="sub-menu">
                    <li><a href="@Url.Action("Index", "Song")">Song</a></li>
                    <li><a href="@Url.Action("Index", "Playlist")">Playlist</a></li>
                </ul>
            </li>
        </ul>
    </header>
    <!-- Header section end -->
    <!-- Playlist section -->

    <section class="playlist-section spad">
        <div class="container-fluid">
            <div class="section-title">
                <h2>Playlists</h2>
            </div>
            <div class="container">
                <ul class="playlist-filter controls">
                    <li class="control" data-filter=".genres">Genres</li>
                    <li class="control" data-filter=".artists">Artists</li>
                    <li class="control" data-filter=".movies">Movies Soundtracks</li>
                    <li class="control" data-filter=".labels">Labels</li>
                    <li class="control" data-filter="all">All Playlist</li>
                </ul>
            </div>
            <div class="clearfix"></div>
            <div class="row playlist-area">
                <div class="mix col-lg-3 col-md-4 col-sm-6 genres">
                    <button class="playlist-button" onclick="window.location.href='@Url.Action("Index", "Song")';">
                        <div class="playlist-item">
                            <img src="/theme/playlist/img/playlist_img/1.jpg" alt="">
                            <h5>Live Concerts</h5>
                        </div>
                    </button>

                </div>
                <!-- Repite el mismo patrón para los otros playlist-item -->
                <div class="mix col-lg-3 col-md-4 col-sm-6 artists">
                    <button class="playlist-button" onclick="window.location.href='@Url.Action("Index", "Song")';">
                        <div class="playlist-item">
                            <img src="/theme/playlist/img/playlist_img/2.jpg" alt="">
                            <h5>Dj Set</h5>
                        </div>
                    </button>
                </div>

                <div class="mix col-lg-3 col-md-4 col-sm-6 movies">
                    <button class="playlist-button" onclick="window.location.href='@Url.Action("Index", "Song")';">
                        <div class="playlist-item">
                            <img src="/theme/playlist/img/playlist_img/3.jpg" alt="">
                            <h5>Recorded Live</h5>
                        </div>
                    </button>
                </div>
                <div class="mix col-lg-3 col-md-4 col-sm-6 genres">
                    <button class="playlist-button" onclick="window.location.href='@Url.Action("Index", "Song")';">
                        <div class="playlist-item">
                            <img src="/theme/playlist/img/playlist_img/5.jpg" alt="">
                            <h5>Rock & Roll</h5>
                        </div>
                    </button>
                </div>


                <div class="mix col-lg-3 col-md-4 col-sm-6 artists">
                    <div class="playlist-item">
                        <button class="playlist-button" onclick="window.location.href='@Url.Action("Index", "Song")';">
                            <div class="playlist-item">
                                <img src="/theme/playlist/img/playlist_img/6.jpg" alt="">
                                <h5>Classic Music</h5>
                            </div>
                        </button>
                    </div>
                </div>
                <div class="mix col-lg-3 col-md-4 col-sm-6 movies">
                    <div class="playlist-item">
                        <button class="playlist-button" onclick="window.location.href='@Url.Action("Index", "Song")';">
                            <div class="playlist-item">
                                <img src="/theme/playlist/img/playlist_img/7.jpg" alt="">
                                <h5>Rock</h5>
                            </div>
                        </button>
                    </div>
                </div>
                <div class="mix col-lg-3 col-md-4 col-sm-6 labels">
                    <div class="playlist-item">
                        <button class="playlist-button" onclick="window.location.href='@Url.Action("Index", "Song")';">
                            <div class="playlist-item">
                                <img src="/theme/playlist/img/playlist_img/8.jpg" alt="">
                                <h5>Alternative</h5>
                            </div>
                        </button>
                    </div>
                </div>
                <div class="mix col-lg-3 col-md-4 col-sm-6 genres">
                    <div class="playlist-item">
                        <button class="playlist-button" onclick="window.location.href='@Url.Action("Index", "Song")';">
                            <div class="playlist-item">
                                <img src="/theme/playlist/img/playlist_img/9.jpg" alt="">
                                <h5>Countryh5>
                            </div>
                        </button>
                    </div>
                </div>
                <div class="mix col-lg-3 col-md-4 col-sm-6 movies">
                    <div class="playlist-item">
                        <button class="playlist-button" onclick="window.location.href='@Url.Action("Index", "Song")';">
                            <div class="playlist-item">
                                <img src="/theme/playlist/img/playlist_img/11.jpg" alt="">
                                <h5>Pop Culture</h5>
                            </div>
                        </button>

                    </div>
                </div>
                <div class="mix col-lg-3 col-md-4 col-sm-6 labels">
                    <div class="playlist-item">
                        <button class="playlist-button" onclick="window.location.href='@Url.Action("Index", "Song")';">
                            <div class="playlist-item">
                                <img src="/theme/playlist/img/playlist_img/12.jpg" alt="">
                                <h5>The 90’s</h5>
                            </div>
                        </button>
                    </div>
                </div>
                <div class="mix col-lg-3 col-md-4 col-sm-6 genres">
                    <div class="playlist-item">
                        <button class="playlist-button" onclick="window.location.href='@Url.Action("Index", "Song")';">
                            <div class="playlist-item">
                                <img src="/theme/playlist/img/playlist_img/13.jpg" alt="">
                                <h5>Jass & Blues</h5>
                            </div>
                        </button>

                    </div>
                </div>
                <div class="mix col-lg-3 col-md-4 col-sm-6 artists">
                    <div class="playlist-item">
                        <button class="playlist-button" onclick="window.location.href='@Url.Action("Index", "Song")';">
                            <div class="playlist-item">
                                <img src="/theme/playlist/img/playlist_img/14.jpg" alt="">
                                <h5>Dj Sets</h5>
                            </div>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Playlist section end -->
    <!-- Footer section -->
    <footer class="footer-section">
        <div class="container">
            <div class="row">
                <div class="col-xl-6 col-lg-5 order-lg-1">
                    <img src="/theme/playlist/img/logo.png" alt="">
                    <div class="copyright">
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer section end -->
    <!--====== Javascripts & Jquery ======-->
    <script src="/theme/playlist/js/jquery-3.2.1.min.js"></script>
    <script src="/theme/playlist/js/bootstrap.min.js"></script>
    <script src="/theme/playlist/js/jquery.slicknav.min.js"></script>
    <script src="/theme/playlist/js/owl.carousel.min.js"></script>
    <script src="/theme/playlist/js/mixitup.min.js"></script>
    <script src="/theme/playlist/js/main.js"></script>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var containerEl = document.querySelector('.playlist-area');
            if (containerEl) {
                mixitup(containerEl);
            }
        });
    </script>
</body>
</html>